@host= http://localhost:3000

GET {{host}}/api/attractions


###
GET {{host}}/api/users/1

###
POST {{host}}/api/users
Content-Type: application/json

{
    "name": "Juanito",
    "surnames": "Perez",
    "email": "juanitoiorrrrr@gmail.com",
    "password": "123456"
}

###

PUT {{host}}/api/users/11
Content-Type: application/json

{
    "name": "Juanan",
    "surnames": "Perez",
    "email": "juanito@gmail.com",
    "password": "123456"
}

###

DELETE {{host}}/api/users/1456789



###

GET {{host}}/api/schedules

###

GET {{host}}/api/schedules/3

###

POST {{host}}/api/schedules
Content-Type: application/json

{

    "start_time": "2024-12-10T10:00:00.000Z",
    "end_time": "2024-12-10T12:00:00.000Z",
    "users_id": 2,
    "attractions_id": 1
    
}

###

PUT {{host}}/api/schedules/3
Content-Type: application/json

{

    "start_time": "2024-12-10T10:00:00.000Z",
    "end_time": "2024-12-10T12:00:00.000Z",
    "users_id": 3,
    "attractions_id": 2
    
}

###

DELETE {{host}}/api/schedules/3