@host= http://localhost:3000

GET {{host}}/api/attractions


###
GET {{host}}/api/users/

###
POST {{host}}/api/users/register
Content-Type: application/json

{
    "name": "Yago",
    "surnames": "Perez",
    "email": "yagio@gmail.com",
    "password": "1234"
}

###

POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "yagio@gmail.com",
    "password": "1234"
}

###

PUT {{host}}/api/users/11
Content-Type: application/json

{
    "name": "Juanan",
    "surnames": "Perez",
    "email": "juanito@gmail.com",
    "password": "123456"
}

###

DELETE {{host}}/api/users/10

###

GET {{host}}/api/comments/schedule/1/comment


###

GET {{host}}/api/comments/schedule/1/comment

###

GET {{host}}/api/schedules/3

###

POST {{host}}/api/schedules
Content-Type: application/json

{

    "start_time": "2024-12-10T10:00:00.000Z",
    "end_time": "2024-12-10T12:00:00.000Z",
    "users_id": 2,
    "attractions_id": 1
    
}

###

PUT {{host}}/api/schedules/3
Content-Type: application/json

{

    "start_time": "2024-12-10T10:00:00.000Z",
    "end_time": "2024-12-10T12:00:00.000Z",
    "users_id": 3,
    "attractions_id": 2
    
}

###

DELETE {{host}}/api/schedules/3